trigger: none

schedules:
- cron: "15 0-2 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: "true"

variables:
- group: huawei

jobs:

- job: build

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      python3 main.py --client huawei --iam --username $USERNAME2 --password $PASSWORD --git $GIT2
    displayName: 'Run'
    env:
      PARENT_USER: atbingbing