trigger: none

#schedules:
#- cron: "45 9-11 * * *"
#  displayName: Daily midnight build
#  branches:
#    include:
#    - master
#  always: "false"

variables:
- group: huawei

jobs:

- job: build
  timeoutInMinutes: 30

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      python3 main.py --client huawei --iam --username $USERNAME20 --password $PASSWORD
    displayName: 'Run'
    env:
      PARENT_USER: atwanding